/*
		This is the bytecode virtual machine.
		It will execute bytecode generated by the compiler.
		The bytecode will be stored in a file.
		The virtual machine will read the bytecode from the file and execute it.

		GC， 垃圾回收机制， 自动释放不再使用的内存，减少内存碎片。
		LCL(life cycle label) 局部变量表，存放函数调用时临时变量的生命周期。

		TODO:
			base Heap-Stack-Machine (slow and easy)
			base Register-Machine	(quick and dirty)
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "joker_c.h"
#include "common.h"
#include "chunk.h"
#include "vm.h"

#include "debug.h"
#include "test.h"

static void repl(VirtualMachine* vm);
static void run_file(VirtualMachine* vm, const char* path);
static char* read_file(const char* path);
int run(int argc, char* argv[]);

/*
* The main entry point of the virtual machine.
* It reads the bytecode from a file and executes it.
* If no file is specified, it enters a REPL (read-eval-print loop).
*/

static void repl(VirtualMachine* vm) {
	char line[1024];

	while (true) {
		printf("> ");

		// read a line of input from the user
		if (!fgets(line, sizeof(line), stdin)) {
			printf("\n");
			break;
		}
		// remove the newline character at the end of the line
		if (line[0] == '\n') continue;
		interpret(vm, line);
	}
}

/*
* Runs the bytecode in a file.
* If there is a compilation or runtime error, it exits with an appropriate status code.
* If there is no file specified, it enters a REPL.
* If there is a file specified, it reads the bytecode from the file and executes it.
*/
static void run_file(VirtualMachine* vm, const char* path) {
	char* source = read_file(path);
	InterpretResult result = interpret(vm, source);
	free(source);

	if (result == interpret_compile_error) exit(enum_compiler_error);
	if (result == interpret_runtime_error) exit(enum_runtime_error);
}

/*
* Reads a file into a buffer.
* If there is an error, it exits with an appropriate status code.
* Returns a pointer to the buffer.
*/
static char* read_file(const char* path) {
	FILE* file = fopen(path, "rb");
	if (file == NULL) {
		fprintf(stderr, "[main::read_file] Error %s:\n\tCould not open file '%s'\n",
			macro_code_to_string(enum_file_error), path);
		exit(enum_file_error);
	}

	fseek(file, 0L, SEEK_END);		// move the file pointer to the end of the file
	size_t file_size = ftell(file);	// get the current position of the file pointer
	rewind(file);					// move the file pointer back to the beginning of the file

	char* buffer = (char*)malloc(file_size + 1);
	if (buffer == NULL) {
		fprintf(stderr, "[main::read_file] Error %s:\n\tCould not allocate memory for file '%s'\n",
			macro_code_to_string(enum_file_error), path);
		exit(enum_file_error);
	}

	size_t bytes_read = fread(buffer, 1, file_size, file);
	if (bytes_read != file_size) {
		fprintf(stderr, "[main::read_file] Error %s:\n\tCould not read file '%s'\n",
			macro_code_to_string(enum_file_error), path);
		exit(enum_file_error);
	}

	buffer[bytes_read] = '\0';		// null-terminate the string

	fclose(file);
	return buffer;
}

int run(int argc, char* argv[]) {
	VirtualMachine vm;
	init_virtual_machine(&vm);

	switch (argc) {
	case 1:
		repl(&vm);
		break;
	case 2:
		run_file(&vm, argv[1]);
		break;
	default:
		fprintf(stderr, "Usage: joker-compiler-c [path]\n");
		exit(enum_invalid_arguments);
	}

	free_virtual_machine(&vm);
	return 0;
}

int main(int argc, char* argv[]) {
	run(argc, argv);
	return 0;
}

int test() {
	// test_op_constant();
	// test_op_constant_long();
	// test_op_negate();
	// test_op_add();
	// test_op_subtract();
	// test_op_multiply();
	// test_expression_1();
	// test_expression_2();
	// test_expression_3();
	// test_expression_4();
	return 0;
}